CREATE TABLE [dbo].[Genre]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(100) NOT NULL
)

GO

CREATE UNIQUE NONCLUSTERED INDEX [NIX_Genre_Name] ON [dbo].[Genre] ([Name])
